version: '3.8'

services:
  app:
    container_name: home-library-app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - custom_network

  db:
    container_name: home-library-db
    build:
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - custom_network

volumes:
  db:
    name: home-library-db-volume
  app:
    name: home-library-app-volume

networks:
  custom_network:
    external: false
    driver: bridge
